name: http_file_transfer_server
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.6.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  device_info_plus: ^11.3.0
  network_info_plus: ^7.0.0
  mime: ^1.0.6
  path: ^1.9.0
  flutter_bloc: ^8.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  

flutter:
  uses-material-design: true
  
  assets:
     - assets/webserver/