name: http_file_transfer_server
description: A simple HTTP file transfer server for Flutter apps. Upload, download, and manage media files with built-in web interface and BLoC integration.
version: 0.0.1
homepage: https://github.com/enesozudogru/http_file_transfer_server
repository: https://github.com/enesozudogru/http_file_transfer_server
issue_tracker: https://github.com/enesozudogru/http_file_transfer_server/issues

environment:
  sdk: ^3.6.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  device_info_plus: ^11.3.0
  network_info_plus: ^7.0.0
  mime: ^1.0.6
  path: ^1.9.0
  flutter_bloc: ^8.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  

flutter:
  uses-material-design: true
  
  assets:
     - assets/webserver/